---

- hosts: localhost
  connection: local
  gather_facts: false
  become: false
  vars_files:
    - vars.yaml

  tasks:
    - name: create fruits file
      template:
        src: templates/fruits.j2
        dest: output/fruits.txt
